# This is a basic workflow to help you get started with Actions
name: Release

# Controls when the workflow will run
on: 
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build and Release APK"
  releases:
    name: Build and Release APK
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Get version from pubspec.yaml
        id: version
        run: echo "::set-output name=version::$(grep "version:" pubspec.yaml | cut -c10-)"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get packages
        run: flutter pub get
              
      - name: Generate Java keystore
        env: 
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo "$KEY_JKS" | base64 --decode > release-keystore.jks 
      
      - name: Create .env file
        run: |
          echo "ANDROID_API_KEY='${{ secrets.ANDROID_API_KEY }}'" > .env
          echo "ANDROID_APP_ID='${{ secrets.ANDROID_APP_ID }}'" >> .env
          echo "ANDROID_MESSAGING_SENDER_ID='${{ secrets.ANDROID_MESSAGING_SENDER_ID }}'" >> .env
          echo "ANDROID_PROJECT_ID='${{ secrets.ANDROID_PROJECT_ID }}'" >> .env
          echo "ANDROID_STORAGE_BUCKET='${{ secrets.ANDROID_STORAGE_BUCKET }}'" >> .env
          echo "API_URL='${{ secrets.API_URL }}'" >> .env
              
      - name: Build APK
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --split-per-abi --release
      
      - name: Build APPBUNDLE
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build appbundle --release

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')"
      
      - name: Release Application
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          body: "Published at ${{ steps.date.outputs.date }}"
          name: "v${{ steps.version.outputs.version }}"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.version }}