name: Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Analyze
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get packages
        run: flutter pub get
        
      - name: Analyze
        run: flutter analyze
    
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@master
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      
      - name: Setup Flutter for Testing
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter Package
        run: flutter pub get
    
      - name: Testing Flutter Project
        run: flutter test --coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=lib/
            -Dsonar.tests=test/
            -Dsonar.projectName=${{ secrets.SONAR_PROJECT_NAME }} 
            -Dsonar.login=${{ secrets.SONAR_LOGIN }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info