name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the feat-prefix branch
  push:
    branches: ['feat/**']
  pull_request:
    branches: ['feat/**']

jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test