name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the feat-prefix branch
  push:
    branches: ['feat/**']
  pull_request:
    branches: ['feat/**']

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: Create .env file
      run: |
        echo "ANDROID_API_KEY='${{ secrets.ANDROID_API_KEY }}'" > .env
        echo "ANDROID_APP_ID='${{ secrets.ANDROID_APP_ID }}'" >> .env
        echo "ANDROID_MESSAGING_SENDER_ID='${{ secrets.ANDROID_MESSAGING_SENDER_ID }}'" >> .env
        echo "ANDROID_PROJECT_ID='${{ secrets.ANDROID_PROJECT_ID }}'" >> .env
        echo "ANDROID_STORAGE_BUCKET='${{ secrets.ANDROID_STORAGE_BUCKET }}'" >> .env
    - run: flutter test